//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdsApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public static Entities _context { get; set; }
        public Entities()
            : base("name=Entities")
        {
        }

        public static Entities GetContext()
        {
            if (_context == null)
                _context = new Entities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Партнёр> Партнёр { get; set; }
        public virtual DbSet<ПродажиПартнёра> ПродажиПартнёра { get; set; }
        public virtual DbSet<Продукт> Продукт { get; set; }
        public virtual DbSet<ТипМатериала> ТипМатериала { get; set; }
        public virtual DbSet<ТипПартнёра> ТипПартнёра { get; set; }
        public virtual DbSet<ТипПродукта> ТипПродукта { get; set; }
    }
}
