//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Партнёр
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Партнёр()
        {
            this.ПродажиПартнёра = new HashSet<ПродажиПартнёра>();
        }
    
        public int ID { get; set; }
        public int ТипПартнёра { get; set; }
        public string Наименование { get; set; }
        public string Директор { get; set; }
        public string ЭлектроннаяПочта { get; set; }
        public string Телефон { get; set; }
        public string ЮридическийАдрес { get; set; }
        public string ИНН { get; set; }
        public Nullable<int> Рейтинг { get; set; }
    
        public virtual ТипПартнёра ТипПартнёра1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПродажиПартнёра> ПродажиПартнёра { get; set; }
    }
}
