//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукт
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукт()
        {
            this.ПродажиПартнёра = new HashSet<ПродажиПартнёра>();
        }
    
        public int ID { get; set; }
        public int ТипПродукта { get; set; }
        public string Название { get; set; }
        public int Артикул { get; set; }
        public double МинКоличество { get; set; }
        public int ТипМатериала { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПродажиПартнёра> ПродажиПартнёра { get; set; }
        public virtual ТипМатериала ТипМатериала1 { get; set; }
        public virtual ТипПродукта ТипПродукта1 { get; set; }
    }
}
