//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПродажиПартнёра
    {
        public int ID { get; set; }
        public int Партнёр { get; set; }
        public int Продукт { get; set; }
        public int КоличествоПродукта { get; set; }
        public int ДатаПродажи { get; set; }
    
        public virtual Партнёр Партнёр1 { get; set; }
        public virtual Продукт Продукт1 { get; set; }
    }
}
